package com.jason.trade.model;

import java.util.Date;

public class Tick {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.currency_id
     *
     * @mbg.generated
     */
    private Integer currencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.lowest_ask
     *
     * @mbg.generated
     */
    private Integer lowestAsk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.higest_bid
     *
     * @mbg.generated
     */
    private Integer higestBid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.percent_change
     *
     * @mbg.generated
     */
    private Integer percentChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.base_vol
     *
     * @mbg.generated
     */
    private Integer baseVol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.quote_vol
     *
     * @mbg.generated
     */
    private Integer quoteVol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.high_24h
     *
     * @mbg.generated
     */
    private Integer high24h;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.low_24h
     *
     * @mbg.generated
     */
    private Integer low24h;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticker.utm_create
     *
     * @mbg.generated
     */
    private Date utmCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.id
     *
     * @return the value of ticker.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.id
     *
     * @param id the value for ticker.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.currency_id
     *
     * @return the value of ticker.currency_id
     *
     * @mbg.generated
     */
    public Integer getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.currency_id
     *
     * @param currencyId the value for ticker.currency_id
     *
     * @mbg.generated
     */
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.price
     *
     * @return the value of ticker.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.price
     *
     * @param price the value for ticker.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.lowest_ask
     *
     * @return the value of ticker.lowest_ask
     *
     * @mbg.generated
     */
    public Integer getLowestAsk() {
        return lowestAsk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.lowest_ask
     *
     * @param lowestAsk the value for ticker.lowest_ask
     *
     * @mbg.generated
     */
    public void setLowestAsk(Integer lowestAsk) {
        this.lowestAsk = lowestAsk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.higest_bid
     *
     * @return the value of ticker.higest_bid
     *
     * @mbg.generated
     */
    public Integer getHigestBid() {
        return higestBid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.higest_bid
     *
     * @param higestBid the value for ticker.higest_bid
     *
     * @mbg.generated
     */
    public void setHigestBid(Integer higestBid) {
        this.higestBid = higestBid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.percent_change
     *
     * @return the value of ticker.percent_change
     *
     * @mbg.generated
     */
    public Integer getPercentChange() {
        return percentChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.percent_change
     *
     * @param percentChange the value for ticker.percent_change
     *
     * @mbg.generated
     */
    public void setPercentChange(Integer percentChange) {
        this.percentChange = percentChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.base_vol
     *
     * @return the value of ticker.base_vol
     *
     * @mbg.generated
     */
    public Integer getBaseVol() {
        return baseVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.base_vol
     *
     * @param baseVol the value for ticker.base_vol
     *
     * @mbg.generated
     */
    public void setBaseVol(Integer baseVol) {
        this.baseVol = baseVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.quote_vol
     *
     * @return the value of ticker.quote_vol
     *
     * @mbg.generated
     */
    public Integer getQuoteVol() {
        return quoteVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.quote_vol
     *
     * @param quoteVol the value for ticker.quote_vol
     *
     * @mbg.generated
     */
    public void setQuoteVol(Integer quoteVol) {
        this.quoteVol = quoteVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.high_24h
     *
     * @return the value of ticker.high_24h
     *
     * @mbg.generated
     */
    public Integer getHigh24h() {
        return high24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.high_24h
     *
     * @param high24h the value for ticker.high_24h
     *
     * @mbg.generated
     */
    public void setHigh24h(Integer high24h) {
        this.high24h = high24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.low_24h
     *
     * @return the value of ticker.low_24h
     *
     * @mbg.generated
     */
    public Integer getLow24h() {
        return low24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.low_24h
     *
     * @param low24h the value for ticker.low_24h
     *
     * @mbg.generated
     */
    public void setLow24h(Integer low24h) {
        this.low24h = low24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticker.utm_create
     *
     * @return the value of ticker.utm_create
     *
     * @mbg.generated
     */
    public Date getUtmCreate() {
        return utmCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticker.utm_create
     *
     * @param utmCreate the value for ticker.utm_create
     *
     * @mbg.generated
     */
    public void setUtmCreate(Date utmCreate) {
        this.utmCreate = utmCreate;
    }
}